package com.increff.teamer.model.constant;

public enum NotificationConstant {
    TEAM,EVENT,CLAIM,REQUEST,INVITE
    ,REQUEST_ACCEPTED,INVITE_REJECTED
    ,REQUEST_REJECTED,INVITE_ACCEPTED
    ,CLAIM_APPROVAL,CLAIM_REJECTED
    ,CLAIM_ACCEPTED,NOTIFY_EVENT,NOTIFY_TEAM,
    PENDING
}
